from enum import IntEnum


class ActionCode(IntEnum):
    # -- ActionCode --
    NO_ACTION = 0
    NO_ACTION_NO_SIGNAL = 1
    NO_ACTION_HOLD = 2

    ENTRY_OK = 100
    ENTRY_FAILED_INVALID_DV01 = 101
    ENTRY_FAILED_INVALID_BOOK = 102
    ENTRY_FAILED_TOO_WIDE = 103
    ENTRY_FAILED_NO_LIQUIDITY = 104
    ENTRY_FAILED_IN_COOLDOWN = 105

    EXIT_TP_OK = 200
    EXIT_TP_OK_WITH_COOLDOWN = 210
    EXIT_FAILED_TP_INVALID_BOOK = 202
    EXIT_FAILED_TP_TOO_WIDE = 203
    EXIT_FAILED_TP_NO_LIQUIDITY = 204

    EXIT_SL_OK = 300
    EXIT_SL_OK_WITH_COOLDOWN = 310
    EXIT_FAILED_SL_INVALID_BOOK = 302
    EXIT_FAILED_SL_NO_LIQUIDITY = 304

    EXIT_TIME_OK = 400
    EXIT_TIME_OK_WITH_COOLDOWN = 410
    EXIT_FAILED_TIME_INVALID_BOOK = 402
    EXIT_FAILED_TIME_NO_LIQUIDITY = 404


class State(IntEnum):
    # -- State --
    STATE_FLAT = 0
    STATE_LONG = 1
    STATE_SHORT = -1
    STATE_TP_COOLDOWN = 2
    STATE_SL_COOLDOWN = 3
    STATE_TIME_COOLDOWN = 4


class TradeType(IntEnum):
    # -- TradeType --
    TRADE_ENTRY = 0
    TRADE_EXIT_TP = 1
    TRADE_EXIT_SL = 2
    TRADE_EXIT_TIME = 3


NO_POSITION_STATES = (
    State.STATE_FLAT.value,
    State.STATE_TP_COOLDOWN.value,
    State.STATE_TP_COOLDOWN.value,
    State.STATE_TIME_COOLDOWN.value,
)
