"""Mean-reversion signal generation module."""

from mlstudy.trading.strategy.alpha.mean_reversion.signals import (
    ExitReason,
    Position,
    SignalConfig,
    SignalStats,
    Trade,
    TradeStats,
    backtest_signal,
    build_signal_dataframe,
    build_trade_blotter,
    build_trade_blotter_with_details,
    compute_backtest_stats,
    compute_signal_stats,
    compute_signal_strength,
    compute_trade_stats,
    ewma_zscore,
    generate_mean_reversion_signal,
    rolling_zscore,
)
from mlstudy.trading.strategy.structures.specs.fly import (
    FlyWeights,
    compute_fly_from_weights,
    enforce_dv01_neutral,
    equal_weight_fly,
    fit_ar1_half_life,
    fly_changes_residual,
    fly_levels_residual,
    fly_optimize_mean_reversion,
    validate_inputs,
)

__all__ = [
    # Signals
    "ExitReason",
    "Position",
    "SignalConfig",
    "SignalStats",
    "Trade",
    "TradeStats",
    "backtest_signal",
    "build_signal_dataframe",
    "build_trade_blotter",
    "build_trade_blotter_with_details",
    "compute_backtest_stats",
    "compute_signal_stats",
    "compute_signal_strength",
    "compute_trade_stats",
    "ewma_zscore",
    "generate_mean_reversion_signal",
    "rolling_zscore",
    # Diagnostics
    "adf_test",
    "compute_half_life",
    "fit_ar1",
    "is_mean_reverting",
    "kpss_test",
    "mean_reversion_diagnostics",
    # Fly construction
    "FlyWeights",
    "compute_fly_from_weights",
    "enforce_dv01_neutral",
    "equal_weight_fly",
    "fit_ar1_half_life",
    "fly_changes_residual",
    "fly_levels_residual",
    "fly_optimize_mean_reversion",
    "validate_inputs",
]
